---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myacart-frontend
spec:
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  replicas: 2
  minReadySeconds: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - name: myappfe
        image: image-registry.openshift-image-registry.svc:5000/default/cart-fe@sha256:e10342b12908ecb7cde5a8a408d5fdd0cd3d89da0e00b0c8dbb4aeeee9dea2d6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.3"
            memory: "300Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: "MY_DB_USER"
            value: "mysqluser"
          - name: "MY_DB_PASS"
            value: "password"
          - name: "MY_DB_NAME"
            value: "mydatadb"
          - name: "MY_DB_HOST_WRITE"
            value: "mysql-0.mysql"
          - name: "MY_DB_HOST_READ"
            value: "mysql-read"



